services:
  keydb:
    image: eqalpha/keydb:latest
    container_name: checkpoint-keydb-full
    ports:
      - "6379:6379"
    volumes:
      - keydb_data:/data
      - ./api/keydb.conf:/usr/local/etc/keydb/keydb.conf:ro
    command: keydb-server /usr/local/etc/keydb/keydb.conf
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
        reservations:
          cpus: '0.2'
          memory: 100M
    healthcheck:
      test: ["CMD", "keydb-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    networks:
      - checkpoint-network

  parser:
    build: 
      context: ./parser
      dockerfile: Dockerfile
    container_name: checkpoint-parser-full
    environment:
      - KEYDB_HOST=keydb
      - KEYDB_PORT=6379
      - KEYDB_PASSWORD=${KEYDB_PASSWORD:-}
    depends_on:
      keydb:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 150M
        reservations:
          cpus: '0.1'
          memory: 50M
    volumes:
      - ./parser/logs:/app/logs
    networks:
      - checkpoint-network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: checkpoint-api-full
    environment:
      - PORT=8080
      - KEYDB_HOST=keydb
      - KEYDB_PORT=6379
      - KEYDB_PASSWORD=${KEYDB_PASSWORD:-}
      - AUTH_USERNAME=${AUTH_USERNAME:-admin}
      - AUTH_PASSWORD=${AUTH_PASSWORD:-checkpoint2025}
      - GIN_MODE=release
      - INSTANCE_ID=api
    depends_on:
      keydb:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 200M
        reservations:
          cpus: '0.3'
          memory: 100M
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    networks:
      - checkpoint-network


  nginx:
    image: nginx:alpine
    container_name: checkpoint-nginx-full
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.loadbalancer.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 100M
        reservations:
          cpus: '0.1'
          memory: 50M
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    networks:
      - checkpoint-network

volumes:
  keydb_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  checkpoint-network:
    driver: bridge


