# ─────────────────────────────────────────────────────────────
# Checkpoint System — Podman Quadlets Management
# ─────────────────────────────────────────────────────────────
#
# Quick start:
#   make env-init   — Create .env from template
#   make tls-init   — Generate Angie config with TLS for your domain
#   make install    — Install quadlet files and reload systemd
#   make build      — Build API and Parser images
#   make start      — Start all services
#
# TLS:
#   make tls-init   — Generate angie.loadbalancer.conf from template
#   make tls-status — Show certificate status
#   make tls-test   — Test TLS handshake and grade
#
# Management:
#   make status     — Show service status
#   make logs       — Follow all logs
#   make health     — Run health checks
#   make test       — Test API endpoints
#   make update     — Pull latest images & restart
#   make clean      — Stop services and remove quadlet files
#   make uninstall  — Full cleanup (services + images + volumes)
#
# ─────────────────────────────────────────────────────────────

# Load .env if exists
-include .env
export

SHELL := /bin/bash
PROJECT_DIR := $(shell pwd)

# Auto-detect root vs rootless Podman
ifeq ($(shell id -u),0)
  # Root: system-wide systemd units
  QUADLET_DIR := /etc/containers/systemd
  SYSTEMCTL   := systemctl
  JOURNALCTL  := journalctl
else
  # Rootless: user systemd units
  QUADLET_DIR := $(HOME)/.config/containers/systemd
  SYSTEMCTL   := systemctl --user
  JOURNALCTL  := journalctl --user
endif

# Service names (generated by Quadlet from .container filenames)
SERVICES := checkpoint-keydb checkpoint-api checkpoint-parser checkpoint-angie

# Domain for TLS certificate (override via .env or CLI: make tls-init DOMAIN=my.domain.com)
DOMAIN ?= checkpoint.truck.kz

# Angie config
ANGIE_CONF     := $(PROJECT_DIR)/angie.loadbalancer.conf
ANGIE_TEMPLATE := $(PROJECT_DIR)/angie.loadbalancer.conf.template
KEYDB_CONF     := $(PROJECT_DIR)/api/keydb.conf

# API auth (loaded from .env via AUTH_USERNAME / AUTH_PASSWORD)
API_USER := $(or $(AUTH_USERNAME),$(error AUTH_USERNAME not set. Run: make env-init && edit .env))
API_PASS := $(or $(AUTH_PASSWORD),$(error AUTH_PASSWORD not set. Run: make env-init && edit .env))
API_URL  := https://$(DOMAIN)
API_URL_HTTP := http://$(DOMAIN)

.PHONY: help env-init install build start stop restart status logs health test update clean uninstall \
        tls-init tls-status tls-test \
        logs-keydb logs-api logs-parser logs-angie

# ─────────────────────────────────────────────────────────────
# Default target
# ─────────────────────────────────────────────────────────────
help: ## Show this help
	@echo ""
	@echo "  Checkpoint System — Podman Quadlets"
	@echo "  ────────────────────────────────────"
	@echo ""
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'
	@echo ""

# ─────────────────────────────────────────────────────────────
# Installation
# ─────────────────────────────────────────────────────────────
install: ## Install quadlet files to systemd and reload
	@echo "📦 Installing Quadlet files..."
	@mkdir -p $(QUADLET_DIR)
	@# Update volume paths to absolute project dir
	@for f in quadlets/*.container quadlets/*.network quadlets/*.volume; do \
		sed "s|%E/border_posts_ext|$(PROJECT_DIR)|g" "$$f" > "$(QUADLET_DIR)/$$(basename $$f)"; \
	done
	@echo "🔄 Reloading systemd..."
	@$(SYSTEMCTL) daemon-reload
	@echo "✅ Installed to $(QUADLET_DIR)"
	@echo ""
	@echo "  Quadlet files:"
	@ls -1 $(QUADLET_DIR)/checkpoint-* 2>/dev/null || echo "  (none found)"
	@echo ""
	@echo "  Generated services:"
	@for svc in $(SERVICES); do \
		if $(SYSTEMCTL) cat $$svc >/dev/null 2>&1; then \
			echo "  ✅ $$svc.service"; \
		else \
			echo "  ❌ $$svc.service NOT generated"; \
			echo "     Debug: $(SYSTEMCTL) cat $$svc"; \
			echo "     Check: /usr/lib/systemd/system-generators/podman-system-generator"; \
		fi; \
	done
	@echo ""
	@echo "  Next: make build && make start"

# ─────────────────────────────────────────────────────────────
# Environment
# ─────────────────────────────────────────────────────────────
env-init: ## Create .env from .env.example
	@if [ -f .env ]; then \
		echo "⚠️  .env already exists. Edit it manually or delete first."; \
	else \
		cp .env.example .env; \
		echo "✅ Created .env from .env.example"; \
		echo "  Edit .env to set DOMAIN, passwords, etc."; \
	fi

# ─────────────────────────────────────────────────────────────
# TLS Certificate Management
# ─────────────────────────────────────────────────────────────
tls-init: ## Generate Angie config with TLS for DOMAIN
	@echo "🔐 Generating TLS config for $(DOMAIN)..."
	@if [ ! -f "$(ANGIE_TEMPLATE)" ]; then \
		echo "❌ Template not found: $(ANGIE_TEMPLATE)"; exit 1; \
	fi
	@sed 's|%%DOMAIN%%|$(DOMAIN)|g' "$(ANGIE_TEMPLATE)" > "$(ANGIE_CONF)"
	@echo "✅ Generated: $(ANGIE_CONF)"
	@echo ""
	@echo "  Domain:      $(DOMAIN)"
	@echo "  Certificate: Let's Encrypt (ACME, auto-renewal)"
	@echo "  Protocol:    TLS 1.3 only"
	@echo "  HTTP/2:      enabled"
	@echo "  HSTS:        max-age=63072000 (2 years)"
	@echo ""
	@echo "  Prerequisites:"
	@echo "    1. DNS A record: $(DOMAIN) → your server IP"
	@echo "    2. Port 80 open (for ACME HTTP-01 challenge)"
	@echo "    3. Port 443 open (for HTTPS)"
	@echo ""
	@echo "  Next: make restart (Angie will auto-obtain certificate)"

tls-status: ## Show TLS certificate status
	@echo ""
	@echo "  TLS Certificate Status"
	@echo "  ──────────────────────"
	@echo "  Domain: $(DOMAIN)"
	@echo ""
	@cert_info=$$(echo | openssl s_client -connect $(DOMAIN):443 -servername $(DOMAIN) 2>/dev/null); \
	if [ -n "$$cert_info" ]; then \
		echo "$$cert_info" | openssl x509 -noout \
			-subject -issuer -dates -fingerprint 2>/dev/null | \
			sed 's/^/  /'; \
		echo ""; \
		expiry=$$(echo "$$cert_info" | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f2); \
		echo "  Expires: $$expiry"; \
		days_left=$$(echo "$$cert_info" | openssl x509 -noout -checkend 0 2>/dev/null && \
			echo "$$cert_info" | openssl x509 -noout -enddate 2>/dev/null | \
			cut -d= -f2 | xargs -I{} bash -c 'echo $$(( ( $$(date -d "{}" +%s) - $$(date +%s) ) / 86400 )) days'); \
		echo "  Days left: $$days_left"; \
	else \
		echo "  ❌ Cannot connect to $(DOMAIN):443"; \
		echo "  Ensure the service is running and DNS is configured."; \
	fi
	@echo ""

tls-test: ## Test TLS handshake and configuration
	@echo ""
	@echo "  TLS Test: $(DOMAIN)"
	@echo "  ──────────────────"
	@echo ""
	@printf "  TLS 1.3 handshake ... "
	@if curl -sf --tlsv1.3 --max-time 5 https://$(DOMAIN)/health > /dev/null 2>&1; then \
		echo "✅"; \
	else \
		echo "❌ (certificate may not be issued yet)"; \
	fi
	@printf "  HTTP→HTTPS redirect . "
	@code=$$(curl -so /dev/null -w '%%{http_code}' --max-time 5 http://$(DOMAIN)/ 2>/dev/null); \
	[ "$$code" = "301" ] && echo "✅ 301" || echo "❌ $$code"
	@printf "  Health on HTTP ...... "
	@curl -sf --max-time 5 http://$(DOMAIN)/health > /dev/null 2>&1 && echo "✅ 200 (no redirect)" || echo "❌ FAIL"
	@printf "  HSTS header ......... "
	@hsts=$$(curl -sI --max-time 5 https://$(DOMAIN)/health 2>/dev/null | grep -i strict-transport | tr -d '\r'); \
	[ -n "$$hsts" ] && echo "✅ $$hsts" || echo "❌ missing"
	@printf "  HTTP/2 .............. "
	@if curl -sI --http2 --max-time 5 https://$(DOMAIN)/health 2>/dev/null | grep -q "HTTP/2"; then \
		echo "✅"; \
	else \
		echo "⚠️  not detected (may need ALPN)"; \
	fi
	@echo ""

# ─────────────────────────────────────────────────────────────
# Build images
# ─────────────────────────────────────────────────────────────
build: ## Build API and Parser container images
	@echo "📥 Pulling external images..."
	@podman pull docker.io/eqalpha/keydb:latest
	@podman pull docker.angie.software/angie:latest
	@echo ""
	@echo "🔨 Building checkpoint-api..."
	@podman build --format docker -t localhost/checkpoint-api:latest -f $(PROJECT_DIR)/api/Dockerfile.prod $(PROJECT_DIR)/api
	@echo ""
	@echo "🔨 Building checkpoint-parser..."
	@podman build --format docker -t localhost/checkpoint-parser:latest -f $(PROJECT_DIR)/parser/Dockerfile $(PROJECT_DIR)/parser
	@echo ""
	@echo "✅ Images built:"
	@podman images --format "  {{.Repository}}:{{.Tag}}  {{.Size}}" | grep -E 'checkpoint|keydb|angie'

# ─────────────────────────────────────────────────────────────
# Service lifecycle
# ─────────────────────────────────────────────────────────────
start: ## Start all Checkpoint services
	@echo "🚀 Starting Checkpoint System..."
	@mkdir -p $(PROJECT_DIR)/parser/logs
	@$(SYSTEMCTL) start checkpoint-keydb
	@echo "  ⏳ Waiting for KeyDB..."
	@sleep 3
	@$(SYSTEMCTL) start checkpoint-api checkpoint-parser
	@echo "  ⏳ Waiting for API..."
	@sleep 3
	@$(SYSTEMCTL) start checkpoint-angie
	@echo "✅ All services started"
	@$(MAKE) --no-print-directory status

stop: ## Stop all Checkpoint services
	@echo "🛑 Stopping Checkpoint System..."
	@$(SYSTEMCTL) stop checkpoint-angie checkpoint-api checkpoint-parser checkpoint-keydb 2>/dev/null || true
	@echo "✅ All services stopped"

restart: ## Restart all services
	@$(MAKE) --no-print-directory stop
	@sleep 2
	@$(MAKE) --no-print-directory start

# ─────────────────────────────────────────────────────────────
# Monitoring
# ─────────────────────────────────────────────────────────────
status: ## Show status of all services
	@echo ""
	@echo "  Checkpoint System Status"
	@echo "  ────────────────────────"
	@for svc in $(SERVICES); do \
		state=$$($(SYSTEMCTL) is-active $$svc 2>/dev/null || echo "inactive"); \
		if [ "$$state" = "active" ]; then \
			printf "  \033[32m●\033[0m %-25s %s\n" "$$svc" "$$state"; \
		else \
			printf "  \033[31m●\033[0m %-25s %s\n" "$$svc" "$$state"; \
		fi; \
	done
	@echo ""
	@echo "  Containers:"
	@podman ps --filter "name=checkpoint" --format "  {{.Names}}\t{{.Status}}" 2>/dev/null || true
	@echo ""

logs: ## Follow logs for all services
	@$(JOURNALCTL) -f -u checkpoint-keydb -u checkpoint-api -u checkpoint-parser -u checkpoint-angie

logs-keydb: ## Follow KeyDB logs
	@$(JOURNALCTL) -f -u checkpoint-keydb

logs-api: ## Follow API logs
	@$(JOURNALCTL) -f -u checkpoint-api

logs-parser: ## Follow Parser logs
	@$(JOURNALCTL) -f -u checkpoint-parser

logs-angie: ## Follow Angie logs
	@$(JOURNALCTL) -f -u checkpoint-angie

# ─────────────────────────────────────────────────────────────
# Health & Testing
# ─────────────────────────────────────────────────────────────
health: ## Run health checks on all services
	@echo ""
	@echo "  Health Checks"
	@echo "  ─────────────"
	@# KeyDB
	@printf "  KeyDB:  "
	@podman exec checkpoint-keydb keydb-cli ping 2>/dev/null && true || echo "❌ FAIL"
	@# API
	@printf "  API:    "
	@curl -sf $(API_URL)/health 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print('✅ ' + d['status'] + ' (keydb: ' + d['keydb_status'] + ')')" 2>/dev/null || echo "❌ FAIL"
	@# Angie
	@printf "  Angie:  "
	@curl -sf $(API_URL)/status 2>/dev/null | head -1 | grep -q "Active" && echo "✅ active" || echo "❌ FAIL"
	@echo ""

test: ## Test API endpoints
	@echo ""
	@echo "  API Tests"
	@echo "  ─────────"
	@echo ""
	@printf "  GET /health ............. "
	@curl -sf $(API_URL)/health > /dev/null && echo "✅ 200" || echo "❌ FAIL"
	@printf "  GET /api/v1/checkpoints . "
	@total=$$(curl -sf -u $(API_USER):$(API_PASS) $(API_URL)/api/v1/checkpoints 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin)['total'])" 2>/dev/null) && echo "✅ $$total checkpoints" || echo "❌ FAIL"
	@printf "  GET /api/v1/stats ...... "
	@curl -sf -u $(API_USER):$(API_PASS) $(API_URL)/api/v1/stats > /dev/null && echo "✅ 200" || echo "❌ FAIL"
	@printf "  GET /api/v1/checkpoints/ids "
	@curl -sf -u $(API_USER):$(API_PASS) $(API_URL)/api/v1/checkpoints/ids > /dev/null && echo "✅ 200" || echo "❌ FAIL"
	@printf "  Compression (brotli) ... "
	@enc=$$(curl -sI -H "Accept-Encoding: br" -u $(API_USER):$(API_PASS) $(API_URL)/api/v1/checkpoints 2>/dev/null | grep -i content-encoding | tr -d '\r'); \
		[ -n "$$enc" ] && echo "✅ $$enc" || echo "⚠️  not compressed"
	@echo ""

# ─────────────────────────────────────────────────────────────
# Updates
# ─────────────────────────────────────────────────────────────
update: ## Pull latest images and restart
	@echo "📥 Pulling latest images..."
	@podman pull eqalpha/keydb:latest
	@podman pull docker.angie.software/angie:latest
	@echo ""
	@echo "🔨 Rebuilding local images..."
	@$(MAKE) --no-print-directory build
	@echo ""
	@echo "🔄 Restarting services..."
	@$(MAKE) --no-print-directory restart

auto-update: ## Enable podman auto-update timer
	@echo "🔄 Enabling podman auto-update..."
	@$(SYSTEMCTL) enable --now podman-auto-update.timer
	@echo "✅ Auto-update enabled. Schedule:"
	@$(SYSTEMCTL) list-timers podman-auto-update.timer 2>/dev/null || true

# ─────────────────────────────────────────────────────────────
# Resource monitoring
# ─────────────────────────────────────────────────────────────
stats: ## Show resource usage
	@echo ""
	@echo "  Resource Usage"
	@echo "  ──────────────"
	@podman stats --no-stream --format "  {{.Name}}\tCPU={{.CPUPerc}}\tMEM={{.MemUsage}}" \
		$(foreach svc,$(SERVICES),$(svc)) 2>/dev/null || echo "  No running containers"
	@echo ""

# ─────────────────────────────────────────────────────────────
# Cleanup
# ─────────────────────────────────────────────────────────────
clean: ## Stop services and remove quadlet files
	@echo "🧹 Cleaning up..."
	@$(MAKE) --no-print-directory stop
	@rm -f $(QUADLET_DIR)/checkpoint-*.container
	@rm -f $(QUADLET_DIR)/checkpoint-*.volume
	@rm -f $(QUADLET_DIR)/checkpoint.network
	@$(SYSTEMCTL) daemon-reload
	@echo "✅ Quadlet files removed, systemd reloaded"

uninstall: clean ## Full cleanup: services + images + volumes
	@echo "🗑️  Removing images..."
	@podman rmi localhost/checkpoint-api:latest 2>/dev/null || true
	@podman rmi localhost/checkpoint-parser:latest 2>/dev/null || true
	@echo ""
	@echo "🗑️  Removing volumes..."
	@podman volume rm checkpoint-keydb-data 2>/dev/null || true
	@podman volume rm checkpoint-angie-logs 2>/dev/null || true
	@echo "✅ Full uninstall complete"

# ─────────────────────────────────────────────────────────────
# Shell access
# ─────────────────────────────────────────────────────────────
shell-keydb: ## Open KeyDB CLI
	@podman exec -it checkpoint-keydb keydb-cli

shell-api: ## Open shell in API container
	@podman exec -it checkpoint-api /bin/sh

shell-angie: ## Open shell in Angie container
	@podman exec -it checkpoint-angie /bin/sh

shell-parser: ## Open shell in Parser container
	@podman exec -it checkpoint-parser /bin/bash
