# ─────────────────────────────────────────────────────────────
# Checkpoint System — Podman Quadlets Management
# ─────────────────────────────────────────────────────────────
#
# Usage:
#   make install    — Install quadlet files and reload systemd
#   make build      — Build API and Parser images
#   make start      — Start all services
#   make stop       — Stop all services
#   make restart    — Restart all services
#   make status     — Show service status
#   make logs       — Follow all logs
#   make health     — Run health checks
#   make test       — Test API endpoints
#   make update     — Pull latest images & restart
#   make clean      — Stop services and remove quadlet files
#   make uninstall  — Full cleanup (services + images + volumes)
#
# ─────────────────────────────────────────────────────────────

SHELL := /bin/bash
PROJECT_DIR := $(shell pwd)
QUADLET_DIR := $(HOME)/.config/containers/systemd
SYSTEMCTL   := systemctl --user

# Service names (generated by Quadlet from .container filenames)
SERVICES := checkpoint-keydb checkpoint-api checkpoint-parser checkpoint-angie

# Angie config needs absolute path for volume mount
ANGIE_CONF := $(PROJECT_DIR)/angie.loadbalancer.conf
KEYDB_CONF := $(PROJECT_DIR)/api/keydb.conf

# API auth
API_USER := admin
API_PASS := checkpoint2025
API_URL  := http://localhost

.PHONY: help install build start stop restart status logs health test update clean uninstall \
        logs-keydb logs-api logs-parser logs-angie

# ─────────────────────────────────────────────────────────────
# Default target
# ─────────────────────────────────────────────────────────────
help: ## Show this help
	@echo ""
	@echo "  Checkpoint System — Podman Quadlets"
	@echo "  ────────────────────────────────────"
	@echo ""
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'
	@echo ""

# ─────────────────────────────────────────────────────────────
# Installation
# ─────────────────────────────────────────────────────────────
install: ## Install quadlet files to systemd and reload
	@echo "📦 Installing Quadlet files..."
	@mkdir -p $(QUADLET_DIR)
	@# Update volume paths to absolute project dir
	@for f in quadlets/*.container quadlets/*.network quadlets/*.volume; do \
		sed "s|%E/border_posts_ext|$(PROJECT_DIR)|g" "$$f" > "$(QUADLET_DIR)/$$(basename $$f)"; \
	done
	@echo "🔄 Reloading systemd..."
	@$(SYSTEMCTL) daemon-reload
	@echo "✅ Installed to $(QUADLET_DIR)"
	@echo ""
	@echo "  Quadlet files:"
	@ls -1 $(QUADLET_DIR)/checkpoint-* 2>/dev/null || echo "  (none found)"
	@echo ""
	@echo "  Next: make build && make start"

# ─────────────────────────────────────────────────────────────
# Build images
# ─────────────────────────────────────────────────────────────
build: ## Build API and Parser container images
	@echo "🔨 Building checkpoint-api..."
	@podman build -t localhost/checkpoint-api:latest -f $(PROJECT_DIR)/api/Dockerfile.prod $(PROJECT_DIR)/api
	@echo ""
	@echo "🔨 Building checkpoint-parser..."
	@podman build -t localhost/checkpoint-parser:latest -f $(PROJECT_DIR)/parser/Dockerfile $(PROJECT_DIR)/parser
	@echo ""
	@echo "✅ Images built:"
	@podman images --format "  {{.Repository}}:{{.Tag}}  {{.Size}}" | grep checkpoint

# ─────────────────────────────────────────────────────────────
# Service lifecycle
# ─────────────────────────────────────────────────────────────
start: ## Start all Checkpoint services
	@echo "🚀 Starting Checkpoint System..."
	@$(SYSTEMCTL) start checkpoint-keydb
	@echo "  ⏳ Waiting for KeyDB..."
	@sleep 3
	@$(SYSTEMCTL) start checkpoint-api checkpoint-parser
	@echo "  ⏳ Waiting for API..."
	@sleep 3
	@$(SYSTEMCTL) start checkpoint-angie
	@echo "✅ All services started"
	@$(MAKE) --no-print-directory status

stop: ## Stop all Checkpoint services
	@echo "🛑 Stopping Checkpoint System..."
	@$(SYSTEMCTL) stop checkpoint-angie checkpoint-api checkpoint-parser checkpoint-keydb 2>/dev/null || true
	@echo "✅ All services stopped"

restart: ## Restart all services
	@$(MAKE) --no-print-directory stop
	@sleep 2
	@$(MAKE) --no-print-directory start

# ─────────────────────────────────────────────────────────────
# Monitoring
# ─────────────────────────────────────────────────────────────
status: ## Show status of all services
	@echo ""
	@echo "  Checkpoint System Status"
	@echo "  ────────────────────────"
	@for svc in $(SERVICES); do \
		state=$$($(SYSTEMCTL) is-active $$svc 2>/dev/null || echo "inactive"); \
		if [ "$$state" = "active" ]; then \
			printf "  \033[32m●\033[0m %-25s %s\n" "$$svc" "$$state"; \
		else \
			printf "  \033[31m●\033[0m %-25s %s\n" "$$svc" "$$state"; \
		fi; \
	done
	@echo ""
	@echo "  Containers:"
	@podman ps --filter "name=checkpoint" --format "  {{.Names}}\t{{.Status}}" 2>/dev/null || true
	@echo ""

logs: ## Follow logs for all services
	@journalctl --user -f -u checkpoint-keydb -u checkpoint-api -u checkpoint-parser -u checkpoint-angie

logs-keydb: ## Follow KeyDB logs
	@journalctl --user -f -u checkpoint-keydb

logs-api: ## Follow API logs
	@journalctl --user -f -u checkpoint-api

logs-parser: ## Follow Parser logs
	@journalctl --user -f -u checkpoint-parser

logs-angie: ## Follow Angie logs
	@journalctl --user -f -u checkpoint-angie

# ─────────────────────────────────────────────────────────────
# Health & Testing
# ─────────────────────────────────────────────────────────────
health: ## Run health checks on all services
	@echo ""
	@echo "  Health Checks"
	@echo "  ─────────────"
	@# KeyDB
	@printf "  KeyDB:  "
	@podman exec checkpoint-keydb keydb-cli ping 2>/dev/null && true || echo "❌ FAIL"
	@# API
	@printf "  API:    "
	@curl -sf $(API_URL)/health 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print('✅ ' + d['status'] + ' (keydb: ' + d['keydb_status'] + ')')" 2>/dev/null || echo "❌ FAIL"
	@# Angie
	@printf "  Angie:  "
	@curl -sf $(API_URL)/status 2>/dev/null | head -1 | grep -q "Active" && echo "✅ active" || echo "❌ FAIL"
	@echo ""

test: ## Test API endpoints
	@echo ""
	@echo "  API Tests"
	@echo "  ─────────"
	@echo ""
	@printf "  GET /health ............. "
	@curl -sf $(API_URL)/health > /dev/null && echo "✅ 200" || echo "❌ FAIL"
	@printf "  GET /api/v1/checkpoints . "
	@total=$$(curl -sf -u $(API_USER):$(API_PASS) $(API_URL)/api/v1/checkpoints 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin)['total'])" 2>/dev/null) && echo "✅ $$total checkpoints" || echo "❌ FAIL"
	@printf "  GET /api/v1/stats ...... "
	@curl -sf -u $(API_USER):$(API_PASS) $(API_URL)/api/v1/stats > /dev/null && echo "✅ 200" || echo "❌ FAIL"
	@printf "  GET /api/v1/checkpoints/ids "
	@curl -sf -u $(API_USER):$(API_PASS) $(API_URL)/api/v1/checkpoints/ids > /dev/null && echo "✅ 200" || echo "❌ FAIL"
	@printf "  Compression (brotli) ... "
	@enc=$$(curl -sI -H "Accept-Encoding: br" -u $(API_USER):$(API_PASS) $(API_URL)/api/v1/checkpoints 2>/dev/null | grep -i content-encoding | tr -d '\r'); \
		[ -n "$$enc" ] && echo "✅ $$enc" || echo "⚠️  not compressed"
	@echo ""

# ─────────────────────────────────────────────────────────────
# Updates
# ─────────────────────────────────────────────────────────────
update: ## Pull latest images and restart
	@echo "📥 Pulling latest images..."
	@podman pull eqalpha/keydb:latest
	@podman pull docker.angie.software/angie:latest
	@echo ""
	@echo "🔨 Rebuilding local images..."
	@$(MAKE) --no-print-directory build
	@echo ""
	@echo "🔄 Restarting services..."
	@$(MAKE) --no-print-directory restart

auto-update: ## Enable podman auto-update timer
	@echo "🔄 Enabling podman auto-update..."
	@$(SYSTEMCTL) enable --now podman-auto-update.timer
	@echo "✅ Auto-update enabled. Schedule:"
	@$(SYSTEMCTL) list-timers podman-auto-update.timer 2>/dev/null || true

# ─────────────────────────────────────────────────────────────
# Resource monitoring
# ─────────────────────────────────────────────────────────────
stats: ## Show resource usage
	@echo ""
	@echo "  Resource Usage"
	@echo "  ──────────────"
	@podman stats --no-stream --format "  {{.Name}}\tCPU={{.CPUPerc}}\tMEM={{.MemUsage}}" \
		$(foreach svc,$(SERVICES),$(svc)) 2>/dev/null || echo "  No running containers"
	@echo ""

# ─────────────────────────────────────────────────────────────
# Cleanup
# ─────────────────────────────────────────────────────────────
clean: ## Stop services and remove quadlet files
	@echo "🧹 Cleaning up..."
	@$(MAKE) --no-print-directory stop
	@rm -f $(QUADLET_DIR)/checkpoint-*.container
	@rm -f $(QUADLET_DIR)/checkpoint-*.volume
	@rm -f $(QUADLET_DIR)/checkpoint.network
	@$(SYSTEMCTL) daemon-reload
	@echo "✅ Quadlet files removed, systemd reloaded"

uninstall: clean ## Full cleanup: services + images + volumes
	@echo "🗑️  Removing images..."
	@podman rmi localhost/checkpoint-api:latest 2>/dev/null || true
	@podman rmi localhost/checkpoint-parser:latest 2>/dev/null || true
	@echo ""
	@echo "🗑️  Removing volumes..."
	@podman volume rm checkpoint-keydb-data 2>/dev/null || true
	@podman volume rm checkpoint-angie-logs 2>/dev/null || true
	@echo "✅ Full uninstall complete"

# ─────────────────────────────────────────────────────────────
# Shell access
# ─────────────────────────────────────────────────────────────
shell-keydb: ## Open KeyDB CLI
	@podman exec -it checkpoint-keydb keydb-cli

shell-api: ## Open shell in API container
	@podman exec -it checkpoint-api /bin/sh

shell-angie: ## Open shell in Angie container
	@podman exec -it checkpoint-angie /bin/sh

shell-parser: ## Open shell in Parser container
	@podman exec -it checkpoint-parser /bin/bash
